[package]
name = "language-server-tl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tower-lsp = "0.18.0"
tokio = { version = "1.25.0", features = ["full"] }