[package]
name = "emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
crossterm = "0.23"
ringbuffer = "0.11.1"

# jit stuff
libc = "0.2.139"

[profile.release]
opt-level = 3